Feature/cloudwatch target
weaveworks/grafanalib pull request #301
Opened 2021-01-05 16:19 UTC by Puneeth-n

## What does this do?

## Why is it a good idea?

## Context

## Questions

2021-01-05 19:29 UTC, Puneeth-n commented
Hi @JamesGibo  @dholbach Can you please review it?

2021-01-06 08:30 UTC, JamesGibo commented on grafanalib/tests/test_cloudwatch.py
> +if sys.version_info[0] < 3:
We probably don't need this as there is no support for py2 now in grafanalib

2021-01-06 08:30 UTC, JamesGibo requested changes
Thanks for your PR it is much appreciated and a feature than many users have requested. 
I don't use cloudwatch myself so have not tested the code but what you have done seems to cover the features defined in the Grafana docs.

Please could you add a note to the changelog about what you have added?

2021-01-08 09:05 UTC, JamesGibo approved these changes
LGTM

2021-01-08 10:37 UTC, merged