Add SQL Target
weaveworks/grafanalib pull request #429
Opened 2021-11-17 13:48 UTC by rjulius23

This change is supposed to make it possible to define SQL queries as well for targets so Data Sources like MySQL, PostgreSQL can work too.

## What does this do?
Creates a New Target class named SqlTarget. With this now it is possible to define panels (Graphs) with SQL queries in them for datasources like MySQL and PostgreSQL.

## Why is it a good idea?
SQL based datasources are really widespread and with this addition now those panels can also be defined by grafanalib.

## Context
It was already mentioned in a feature request.  Feature Request: support sql queries #153 

## Questions
No questions from my side.

2021-11-17 15:07 UTC, rjulius23 commented on grafanalib/core.py
```suggestion


```

2021-11-17 15:07 UTC, rjulius23 commented on grafanalib/core.py
Fix pep8

2021-11-17 15:59 UTC, JamesGibo requested changes
PR looks look other than the minor linting issues.

Please could you add a test to check that the new SqlTarget class serialises and add a docstring for each of the attributes and how to use it?

I have not used SQL with grafana, but would `rawQuery` every need to be set to False? If yes, please could you make it an attribute?

2021-11-17 16:05 UTC, rjulius23 commented
> PR looks look other than the minor linting issues.
> 
> Please could you add a test to check that the new SqlTarget class serialises and add a docstring for each of the attributes and how to use it?
> 
> I have not used SQL with grafana, but would `rawQuery` every need to be set to False? If yes, please could you make it an attribute?

rawQuery has to be True is you used rawSql, the reason for that is that you can also use the graphical interface to compose an SQL, but obviously it is easier in code to provide the SQL command :)

I will add test and docstrings.

2021-11-17 22:06 UTC, rjulius23 commented
> PR looks look other than the minor linting issues.
> 
> Please could you add a test to check that the new SqlTarget class serialises and add a docstring for each of the attributes and how to use it?
> 
> I have not used SQL with grafana, but would `rawQuery` every need to be set to False? If yes, please could you make it an attribute?

Updated with unit test and docstrings.

2021-11-18 07:36 UTC, rjulius23 commented
My bad, fixing the test.

2021-11-18 07:38 UTC, JamesGibo commented
> My bad, fixing the test.

No worries, you can test locally using tox by running `make all`

2021-11-18 10:55 UTC, rjulius23 commented
> > My bad, fixing the test.
> 
> No worries, you can test locally using tox by running `make all`

Test are fixed, I also added an example that I have tested on my Grafana to be sure.

2021-11-18 10:58 UTC, rjulius23 commented on grafanalib/core.py
> +    rawQuery = attr.ib(default=True)
@JamesGibo I added the rawQuery, but in the docstring I highlighted that it should be True , now the by default is True.

2021-11-18 13:43 UTC, JamesGibo approved these changes
LGTM, thanks for the PR and dashboard example

2021-11-18 13:43 UTC, merged