TimeSerie option ( Min, Max, Decimals )
weaveworks/grafanalib pull request #501
Opened 2022-05-25 11:34 UTC by vcandeau

## What does this do?
[ADD] Minimun options for Timeseries
[ADD] Maximun options for Timeseries
[ADD] Number of decimals displays options for Timeseries

## Why is it a good idea?
Give ability to adjust the watch size of the grid

## Context
Answering the issue [474](https://github.com/weaveworks/grafanalib/issues/474)

2022-05-25 11:37 UTC, JamesGibo requested changes

2022-05-25 11:37 UTC, JamesGibo commented on grafanalib/core.py
> +    :param valueMax: Minimun value for Panel
```suggestion
    :param valueMax: Maximum value for Panel
```

2022-05-25 11:37 UTC, JamesGibo commented on CHANGELOG.rst
> +* Added Number of decimals displays option for Timeserie
```suggestion
* Added Minimum option for Timeseries
* Added Maximum option for Timeseries
* Added Number of decimals displays option for Timeseries
```

2022-05-25 11:44 UTC, vcandeau commented
Done regardless to your suggestion @JamesGibo

2022-05-25 14:38 UTC, JamesGibo commented on grafanalib/core.py
> +    :param valueMax: Minimum value for Panel
```suggestion
    :param valueMax: Maximum value for Panel
```

2022-05-25 16:40 UTC, vcandeau commented
Fix

2022-08-30 11:00 UTC, cristifalcas commented
Any traction for this? We also hit this issue

2022-09-01 21:33 UTC, cristifalcas commented
ping @vcandeau :)

2022-09-08 11:07 UTC, vcandeau commented
No response on the fix after reviewing

2022-09-08 14:07 UTC, vcandeau commented
For me it's done and working just need to be merge

2022-12-24 03:19 UTC, be-hase commented
@JamesGibo 
could you check this PR? I want to use min&max option.

2023-03-03 06:16 UTC, fzyzcjy commented
Is there any updates? Thanks

2023-05-18 09:10 UTC, JamesGibo approved these changes
LGTM

2023-05-18 09:10 UTC, merged