Add support for `statistic` field in `CloudwatchMetricsTarget`
weaveworks/grafanalib pull request #543
Opened 2022-11-09 13:47 UTC by Butterneck

## What does this do?
Add support for `statistic` field in `CloudwatchMetricsTarget`

## Why is it a good idea?
The existing `statistics` field is being ignored by grafana 9.x, it must be named `statistic` (not `statistics`) and must be a string (not a list)

2022-11-14 08:09 UTC, JamesGibo requested changes
Thanks for this PR, I do not use cloudwatch so will have to trust that this is required, but as this is not a breaking change I am happy to add it.
Please could you add a little description of what the difference is between the 2 fields to the doc strings?

2022-11-14 08:09 UTC, JamesGibo commented on grafanalib/cloudwatch.py
> +    :param statistic: Cloudwatch mathematic statistic
Please could you add a note about why there are 2 fields ( < v9 and > v9 for example) and the difference in formatting (list vs string)?

2023-03-17 12:42 UTC, tiansu-yu-idealo commented on grafanalib/cloudwatch.py
> +    :param statistics: Cloudwatch mathematic statistics
Unsolicited advise: Should there be a message e.g. `(to be deprecated, prefer `statistic` instead)`

2023-05-18 09:15 UTC, JamesGibo requested changes

2023-05-18 09:15 UTC, JamesGibo commented on grafanalib/cloudwatch.py
> +    :param statistics: Cloudwatch mathematic statistics
```suggestion
    :param statistics: Cloudwatch mathematic statistics (to be deprecated, prefer `statistic` instead)
```

2023-05-18 09:15 UTC, JamesGibo approved these changes

2023-05-18 09:15 UTC, JamesGibo commented on grafanalib/cloudwatch.py
> +    :param statistic: Cloudwatch mathematic statistic
Added a note to show `statistics` deprecated

2023-05-18 09:16 UTC, merged